//测试案例抛出Fail异常来指示测试失败的情况，这个类不对外，测试者只能通过assert等接口来抛Fail，也不能显式catch
class Fail
{
    public String s usemethod(str);
}

public void assert(bool cond, String s)
{
    if (!cond)
    {
        throw(new Fail{s});
    }
}
