# **异常处理**

在‘3.5.程序执行’中已经详细说明了Larva的异常机制，本节主要说明异常相关的内建语法元素

## **异常的抛出**

Larva的异常类是指一个实现了`Throwable`接口的类，一般所说的“异常”是指异常类的对象实例

`Throwable`接口的定义很简单，实际上就是继承了`Stringable`接口：
```
public interface Throwable
{
    /*
    返回异常对象包含的信息，或异常本身的描述
    */
    public String str();
}
```

异常的抛出可以使用内建函数`throw`：
```
/*
抛出异常
*/
public void throw(Throwable t)
```
`throw`函数将设置其栈帧的异常为传入的参数`t`，并将其上抛，从逻辑上也可认为是立即中断当前执行并抛出异常，由于异常在`defer`的时候才捕获，
因此当前函数或方法中`throw`之后的代码不会再被执行

*Note*：
* 由于很多类都实现了`Stringable`接口，这也意味着这些类的对象实例都能作为异常抛出，但实际上它们并不一定是一个异常，或适合作为一个异常
* 虽然字符串本身也实现了`Throwable`接口，将其直接作为异常（信息）抛出也是比较合乎逻辑，但这个异常类型太泛了（只是一个信息），一般也不推荐使用

## **异常的捕获**

### **Catched类**

`Catched`是一个泛型类，是异常对象+traceback的封装，Larva在捕获异常时会捕获到这个类的对象实例

```
/*
封装异常对象+traceback
T必须是一个实现了Throwable接口的类
*/
public class Catched<T>
{
    /*
    重新抛出此异常，需要注意对于一个本类型对象c，“c.rethrow()”和“throw(c.throwed())”的区别：
    - rethrow方法会原样上抛，就好像没有被捕获到过一样
    - 取throwed再throw是在当前位置重新将异常抛出

    需要特别注意：
        rethrow重新抛出的只是将此对象包含的异常和traceback重新打包，而不是重新抛出this本身
    */
    public void rethrow()

    /*
    返回包含的异常
    */
    public T throwed()

    /*
    返回traceback，是一个格式化好的字符串，只用于日志打印和人工排错
    */
    public String traceback()
}
```

### **直接捕获**

Larva提供了`handle_exc`内建函数和相关内建语法元素来实现直接捕获，使用方式可参考‘3.5.程序执行’，这里只对相关语法元素进行说明

```
/*
异常处理接口，用于handle_exc
*/
public interface ExcHandler<T>
{
    /*
    处理捕获到的异常
    */
    public void handle(Catched<T> catched_exc);
}

/*
捕获指定类型T的异常并调用handler的handle方法进行处理，需要和defer搭配使用，规则：
- 若无异常则不做操作（即也不会调用handler.handle(nil)，换句话说handle方法的参数不会是nil）
- 若有异常但不能转为T类型，则继续上抛，就像没有捕获过一样
- 若成功捕获到类型T的异常：
    - 若handler为nil，则忽略捕获的异常，相当于handler.handle是一个空方法
    - 否则调用handler.handle(catched_exc)处理异常
*/
public void handle_exc<T>(ExcHandler<T> handler)

/*
忽略所有异常，用于defer中，相当于handle_exc<Throwable>(nil)的简写
*/
public void ignore_exc()
```

### **返回值捕获**

Larva提供了另一个内建函数，可以使得异常像错误返回一样被处理：
```
/*
调用输入的Callable对象的call方法，规则：
- 如果callee.call()的执行中没有出现异常，则返回nil
- 否则根据异常对象进行处理：
    - 若异常可以转为类型T，则以返回值的形式返回捕获的Catched<T>对象实例
    - 否则将异常上抛
*/
public Catched<T> call_and_catch<T>(Callable callee)
```

具体使用规则也可参考‘3.5.程序执行’

## **内建异常**

针对一些通用、常用的异常，Larva将其加入到了`__builtins`模块中作为内建类，方便开发者直接使用，这也有助于统一代码行为和风格，
本小节对这些异常类进行说明

注：由于异常类都是实现了`Throwable`接口，因此以下说明中，如异常的public方法只有一个`str`，则不列出代码
（这意味着构造方法也不是public的，使用者不可直接创建）

* `EmptyException`

    `EmptyException`是一个空异常类型，其`str`方法永远返回空串，作为异常本身来说，它并没有什么使用上的意义，一般是用于简单实现其他异常类型

    例如：
    ```
    class MyExc
    {
        EmptyException e usemethod;
    }
    ```
    这适用于使用者不关心异常的信息，而只关注异常类型的情形，例如通过`MyExc`来指示一些特别的错误，而不需要包含任何信息

* `TypeAssertionError`

    应用于内建函数`assert_type<T>`，当类型断言失败时抛出，`str`方法返回具体的类型断言的失败信息

* `IndexError`

    下标越界错误，即在下标越界时抛出，或类似下标的语法元素越界时抛出

    ```
    public class IndexError
    {
        /*
        构造方法，传入出错的下标值
        */
        public IndexError(long i)

        /*
        输出出错下标值的字符串表示
        */
        public String str()
    }
    ```

    除了通过`throw`直接抛出`IndexError`外，Larva额外提供了内建函数`throw_on_index_error`用于下标越界的快捷判断和异常抛出：
    ```
    /*
    若传入的len不为负，且0<=idx<len，则直接返回，否则以idx为错误下标抛出IndexError
    */
    public void throw_on_index_error(long len, long idx)
    ```

    *Note*：`IndexError`本意应为索引错误，在这里特指为下标错误，用这个名字是因为来自于Python

* `RangeError`

    下标范围错误，主要用于下标范围类的操作，如数组的`slice`、字符串的`sub_str`等

    ```
    public class RangeError
    {
        /*
        构造方法
        参数说明：
        - len：     范围的合法长度
        - begin：   范围起始下标
        - end：     范围结束下标
        */
        public RangeError(long len, long begin, long end)

        /*
        返回范围错误信息，格式“[len][begin:end]”
        */
        public String str()
    }
    ```

    除了通过`throw`直接抛出`RangeError`外，Larva额外提供了内建函数`throw_on_range_error`用于下标范围的快捷判断和异常抛出：
    ```
    /*
    若传入的len不为负，且0<=begin<=end<=len，则直接返回，否则以这三个参数抛出RangeError异常
    */
    public void throw_on_range_error(long len, long begin, long end)
    ```

    需要注意这里的`begin`和`end`的取值可以等于`len`，这是跟下标越界规则不同的地方

* `KeyError`

    键错误，一般是指在通过键查找数据的结构中，查找之类的过程找不到给定键的错误，例如`util.HashMap`的`get`或`pop`操作

    ```
    public class KeyError
    {
        /*
        构造方法，传入参数为出错的键信息，一般可以传入键的字符串表示形式
        */
        public KeyError(String key)

        /*
        返回的错误信息即为构造本异常的键字符串
        */
        public String str()
    }
    ```

* `ValueError`

    值错误，应用比较广泛，例如在输入检查中，若输入的数值不合法，则可以抛出这个异常

    ```
    public class ValueError
    {
        /*
        构造方法，传入参数为错误信息描述
        */
        public ValueError(String info)

        /*
        返回错误信息描述
        */
        public String str()
    }
    ```

* `GoError`

    `GoError`是一个Go的`error`类型的封装，一般用于Larva封装Go代码的地方，可简单地将Go层面返回的错误简单转换成Larva的异常对象

    ```
    public class GoError
    {
        /*
        返回错误信息格式为：“[GoError]Go的error的Error方法返回的错误信息”
        */
        public String str()

        /*
        直接返回this，这个方法是为了实现GoErrorPorter接口
        */
        public GoError go_err()

        /*
        用Native字段存储Go的error
        */
        !<<
        err error
        !>>
    }
    ```

    注意这个异常类没有构造方法，因为创建它必须传入一个Go的`error`值，意即必须在Native代码中进行，直接采用对`err`字段赋值来创建即可

    实际开发中一般并不直接使用`GoError`类，因为这个类型本身太泛了，常规做法是对其做封装，例如：
    ```
    public class MyGoError
    {
        GoError ge usemethod;
    }
    ```
    这样不但能封装`error`值，在Larva层也能做不同类型的区分

## **其他内建元素**

* `GoErrorPorter`

    这是一个接口，表示实现它的异常类是封装了一个Go的`error`

    ```
    public interface GoErrorPorter
    {
        public GoError go_err();
    }
    ```

    如上所述，显然`GoError`本身是实现了这个接口的，因此如果一个异常类是封装了`GoError`，则只要对`go_err`这个方法做usemethod即可

    `GoErrorPorter`的主要作用是可以在Native代码中简化Go的错误和Larva的异常的转换，或一些相关场景下的判断

* `throw_go_error_porter_on_err<E>`

    这个泛型函数提供了一种简便的办法来直接抛出对GoError做封装的类的实例

    ```
    /*
    通过一个简单约定来简化各种GoErrorPorter的抛出实现
    规则：
    - E是一个异常类型并实现了GoErrorPorter接口
    - E必须有一个字段是GoError类型，且名字为“ge”（不要求是public的，这里用Native代码直接赋值）
    - 若go_err为nil则什么都不做，否则go_err必须能断言为Go的error类型，并将用其构造GoError对象并赋值给“ge”字段

    虽然说满足了规则的类型E都可以正常编译执行，但实际上E的定义中都应该直接用代码：
        GoError ge usemethod;
    */
    public void throw_go_error_porter_on_err<E>(GoAny go_err)
    ```

    需要注意的是这是个泛型函数，意味着只能在Larva代码层面调用它（编译器需要识别并生成泛型函数实例），而Go的`error`又是在Native代码层得到的，
    因此大部分应用下都会做一些简单封装，例如常见的一种模式是：
    ```
    public class Error
    {
        GoError ge usemethod;
    }

    void throw_on_go_err(GoAny go_err)
    {
        throw_go_error_porter_on_err<Error>(go_err);
    }
    ```
    然后在本模块Native代码中可直接：
    ```
    err := GO_FUNC_CALL()
    lar_func_@<<throw_on_go_err>>(lar_fiber, err)
    ```
